abstract: Compute SHA1 message digest of uploads
author: E<AElig>var ArnfjE<ouml>rE<eth> Bjarmason <avar@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Plugin-Upload-SHA1
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.2
  Digest::SHA1: 0
version: 0.01
