abstract: L<Catalyst::Plugin::Upload::SHA1> example application
author: "\xC3\x86var Arnfj\xC3\xB6r\xC3\xB0 Bjarmason <avar@cpan.org>"
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Upload-SHA1
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.7006
  Catalyst::Plugin::Upload::SHA1: 0.01
  Catalyst::View::TT: 0.24
version: 0.01
